# Generated by Django 2.2.13 on 2020-07-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=256)),
                ('age', models.IntegerField()),
                ('gender', models.IntegerField()),
                ('via_sns_type', models.IntegerField()),
                ('via_sns_name', models.CharField(max_length=15)),
            ],
        ),
    ]
