# Generated by Django 2.2.7 on 2020-06-22 14:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail_url', models.ImageField(blank=True, upload_to='club/%Y/%m/%d')),
                ('name', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(max_length=50)),
                ('period', models.DateField(max_length=50)),
                ('start_time', models.DateTimeField()),
                ('min_participant_num', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('max_participant_num', models.IntegerField()),
            ],
        ),
    ]
