# Generated by Django 2.2.13 on 2020-07-18 12:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_auto_20200704_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='club',
            name='max_participant_num',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
