# Generated by Django 2.2.13 on 2020-07-29 13:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_auto_20200718_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='max_participant_num',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
    ]
