# Generated by Django 2.2.13 on 2020-08-29 07:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('club', '0004_auto_20200729_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='like_clubs', to=settings.AUTH_USER_MODEL),
        ),
    ]
