# Generated by Django 2.2.13 on 2020-08-29 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_club_like_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='like_users',
            new_name='likes_user',
        ),
    ]
