# Generated by Django 2.2.13 on 2020-08-29 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_auto_20200829_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='likes_user',
            new_name='like_users',
        ),
    ]
